name: API tests in Docker with Allure HTML

on:
  workflow_dispatch:

jobs:
  docker-tests:
    runs-on: ubuntu-latest

    steps:
      # 1. Забираем код
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Собираем Docker-образ
      - name: Build Docker image
        run: |
          docker build -t petstore-tests .

      # 3. Запускаем тесты в контейнере
      - name: Run tests inside Docker
        run: |
          docker run --rm \
            -v ${{ github.workspace }}/allure-results:/app/allure-results \
            petstore-tests

      # 4. Устанавливаем Java (нужна для Allure)
      - name: Install Java
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jre

      # 5. Устанавливаем Allure CLI
      - name: Install Allure
        run: |
          curl -o allure.tgz -Ls https://github.com/allure-framework/allure2/releases/download/2.27.0/allure-2.27.0.tgz
          sudo tar -zxvf allure.tgz -C /opt/
          sudo ln -s /opt/allure-2.27.0/bin/allure /usr/bin/allure

      # 6. Генерация Allure HTML
      - name: Generate Allure HTML report
        run: |
          allure generate allure-results -o allure-report --clean

      # 7. Сохраняем Allure HTML
      - name: Upload Allure HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-report
          path: allure-report